const coinSettings = [
    {
        symbol:'ETHBUSD',
        price:2,
        quantity:2
    },
    {
        symbol:'BNBBUSD',
        price:2,
        quantity:2
    },
    {
        symbol:'LTCBUSD',
        price:2,
        quantity:2
    },
    {
        symbol:'AVAXBUSD',
        price:3,
        quantity:1
    },
    {
        symbol:'APEBUSD',
        price:3,
        quantity:1
    },
    {
        symbol:'SOLUSDC',
        price:2,
        quantity:2
    },
    {
        symbol:'BNBUSDC',
        price:2,
        quantity:2
    }
]

export default coinSettings